# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Stage.create(:id => 1, :level => 1, :name => "Dining Hall", :description => "I'll be friendly to you today, here is where you can learn how this whole thing works. This is prison, no non-sense here. In each situation you will deal with another inmate. You can cooperate with them, or betray them. You can read what the outcome is, if the outcome is good for you, say you eat some good food or please the officer, you will lose some prison time. If you screw up, say you get injured and there is no one to help, you will gain some prison time. In dining hall, you won't gain or lose anything, here is were you practice. Look at the prisoner on the right side, he wants the five cigarretes you have with you from outside. You can put them in the plate and slip it to him under the table (cooperate). He will slip in a plate full of medication for you, it will come in handy later. You also have the option of slipping in an empty plate, and keep the cigarettes (betray), but beware her could also hand you an empty plate. This is prison business, cheating will get you more stuff, but can also screw you over. Try it yourself: you won't lose anything in the Dining Hall.")
Stage.create(:id => 2, :level => 2, :name => "Kitchen", :description => "You are serving soup to the inmate next to you.  You have the choice to give either the good stuff (cooperate), or the standard prison crap (betray). Your cellmate is serving bread next to you - and he faces the same choices, he can give you the fresh bread (cooperate) or the moldy bread (betray).  Remember that you will provide him with soup, and he will provide you with bread.  If you both give each other the good stuff, you both get good food and stay healthy and get to knock off 3 weeks from your sentence later.  If you shaft him with the crappy soup (keeping the good stuff for yourself), and he gives you the good bread, you get to knock off 5 weeks, but he is going to be sick and gains 2 more weeks in here (and vice versa if you give good, and he gives you crap).  Finally, if you both screw each other over with the standard food, nothing changes, same old same.")
Stage.create(:id => 3, :level => 3, :name => "Cell", :description => "It is cleaning day - and you need to clean another inmate's toilet, and he yours.  If you both clean (cooperate), the guards will be satisfied and each of you reduces your sentence by 6 weeks.  If you take advantage of him and shirk (betray) while he still cleans your toilet, you knock off 8 weeks while he gains two weeks (and vice versa if you clean and he doesn't).  If both of you shirk, the guards will not be pleased, you will get punished but no prison time is added.")
Stage.create(:id => 4, :level => 4, :name => "Yard", :description => "It is 5AM. Time to rebuild the wall in the yard.  You and your cellmate are responsible for rebuilding the wall. If either or both of you build (cooperate), the wall will be completed - and each of you will get 6 weeks off your sentence. However, if only one person builds, while the other slacks (betrays), the wall will still get built, but the slacker will have taken advantage, getting 12 weeks off, while the honest worker will have exhausted himself and not receive any time off his sentence. Caution: That wall better be built by tonight cause if neither of you builds, no wall will be formed and that will piss off the guards and both of you will gain 12 more weeks of jail time.")
Stage.create(:id => 5, :level => 5, :name => "Hospital", :description => "You and your cellmate are on duty.  To try and escape duty, you can try to get sent to the hospital by injuring yourself with a piece of glass.  If you do so (betray), while your cellmate does nothing (cooperates), you get to reduce your jail time by 20 weeks while your cellmate needs to do extra work - adding on 8 weeks to his sentence (and vice versa if he injures himself while you don't do anything).  If both of you do nothing, you each do half the work and thus get 12 weeks off each for good behavior.  However, if both of you try to pull the 'injure thyself' stunt, you will be injured with no one to help, and no good will come out of it - your sentences are unchanged and you will suffer from injuries.")
Stage.create(:id => 6, :level => 6, :name => "Office", :description => "You and your accomplice are hauled into different interrogation rooms. You have the chance to either implicate your partner or stay silent. If you implicate him(betray), while he stays silent (cooperates), you will be deemed innocent and get 16 weeks off your sentence while your partner will have 4 weeks added on.  Likewise, if you stay silent, but he implicates you, you will add 4 weeks. If you both stay silent, both of you will get 12 weeks off since the authorities cannot do much with silence. Finally, if you both implicate the other, neither of your sentences will change.")
